### ISSUE TITLE
Tag for Java 17/Tomcat 10?

### ISSUE THREAD

**Issue by srstsavage** [Unidata/tomcat-docker#109]
As of v2.19, ERDDAP requires Java 17 and Tomcat 10.

https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html#changes2.19

https://github.com/axiom-data-science/docker-erddap uses tomcat-docker as the base image, so I'm investigating the appetite for cultivating a `unidata/tomcat-docker:10-jdk17-openjdk` release based on `tomcat:10-jdk17`.

Is the willingness to include this variant? Would it become the `latest` branch? etc

**Comment by julienchastang** [comment]
It seems like this could exist in parallel to the current branches. `latest` may stay as it is though. (ping @robertej09 )

**Comment by ana-v-espinoza** [comment]
Agreed with Julien. We can add a new branch to this repo that's based on `tomcat:10-jdk17`. Will see about getting to this next week.

**Comment by srstsavage** [comment]
One note, `tomcat:10-jdk17` is based on Ubuntu Jammy and is incompatible with older Docker engines.

https://github.com/docker-library/tomcat/issues/269

So, we may want to offer a variant based on `10.0-jdk17-temurin-focal` as well (I verified that it's compatible with older engines). Only difference should be in the `FROM` line for the base image.

**Comment by ana-v-espinoza** [comment]
Closed by #112
