### ISSUE TITLE
Support for Tomcat 10?

### ISSUE THREAD

**Issue by vinisalazar** [Unidata/tomcat-docker#113]
Hi,

Would it be possible to have this image support Tomcat 10 and Java 17? I'm not sure, but could it be a case of simply switching the base image to one of the [latest versions](https://hub.docker.com/_/tomcat)?

This would allow downstream support of the ERDDAP Docker image to update to the latest version (see axiom-data-science/docker-erddap#60).

Thanks in advance!
Vini

**Comment by ana-v-espinoza** [comment]
Hey Vini,

Our latest tag currently inherits from `tomcat:8.5-jdk11-openjdk`, but we also have a couple of branches dedicated to Tomcat 10/Java 17. Find them on Dockerhub:
https://hub.docker.com/r/unidata/tomcat-docker/tags

Additionally, take a look at Issue #109 and the resulting PR #112 for a mechanism to add branches to this repo which will inherit from different upstream tomcat images.

Let us know if there's something else we can do to help, or else close this issue.

Thanks,
Ana

**Comment by vinisalazar** [comment]
Thanks a lot Ana!
