### ISSUE TITLE
Regarding uid/gid

### ISSUE THREAD

**Issue by kwilcox** [Unidata/tomcat-docker#34]
As mentioned by @julienchastang https://github.com/Unidata/thredds-docker/issues/100#issuecomment-257925105, files written inside of the container (logs, etc.) are going to use the `uid/gid` of the `tomcat` user **inside** of the container. This means that if a user mounts a volume to track logs or other files the permissions will not align well with the host. I recommend creating two new parameters that can be set on image run: `USER_UID` and `USER_GID`. In `entrypoint.sh` we can set the tomcat user's `uid` and `gid` to those passed in values (with sensible defaults that are greater than 1000). The container will then write files with a `uid` and `gid` known to the host container.

I've seen this done in other containers but can't find an example right now... will post back when I come across one in the wild.

**Warning**: I have no idea how this would work on Windows or MacOS

**Comment by julienchastang** [comment]
@kwilcox (related to @rsignell-usgs https://github.com/Unidata/thredds-docker/issues/100#issuecomment-267792877)Thanks for the suggestion. I would gladly take a PR in this area. This remains a particularly weak spot as far Docker is concerned and I'm hoping to see a built-in solution from the folks at Docker soon. On windows and macos you run on VM intermediates, but the devil will be in the details.
