### ISSUE TITLE
unidata/tomcat-docker:8.5 failing?

### ISSUE THREAD

**Issue by julienchastang** [Unidata/tomcat-docker#50]
[as reported here](https://github.com/Unidata/tomcat-docker/pull/49#issuecomment-366068552) by @kwilcox

**Comment by kwilcox** [comment]
@julienchastang Are you using the `overlay` or the `aufs` storage driver in your `docker` setup?

**Comment by julienchastang** [comment]
`aufs` but I have been dissatisfied with it: [A](https://github.com/Unidata/xsede-jetstream/issues/161), [B](https://github.com/docker-library/tomcat/issues/35#issuecomment-321876794), [C](https://github.com/Unidata/thredds-docker/issues/177), [D](https://github.com/Unidata/thredds-docker/issues/171).   

Which one are you using?

**Comment by kwilcox** [comment]
I'm absolutely stunned. This took me awhile. I was able to reduce the noise and boil this down to failing only on kernels lower than `3.16`. Anything below `3.16` will consistently fail with the same error. I think it is a combination of a admittedly old kernel, `aufs` and `gosu`.

### aufs / kernel 3.14
```
tomcat@9eee78856f0d:~$ ls -la /usr/local/tomcat/bin
ls: cannot open directory '/usr/local/tomcat/bin/': Permission denied
```

### aufs / kernel 3.16
```
tomcat@9b6456e42303:~$ ls -la /usr/local/tomcat/bin
total 404
drwxr-x---  2 tomcat tomcat   4096 Feb 16 15:28 .
drwxr-sr-x 25 tomcat tomcat   4096 Feb 16 15:28 ..
-rw-r-----  1 tomcat tomcat  34942 Feb  6 23:10 bootstrap.jar
-rw-r-----  1 tomcat tomcat   1664 Feb  6 23:12 catalina-tasks.xml
-rwxr-x---  1 tomcat tomcat  23325 Feb 15 18:55 catalina.sh
-rw-r-----  1 tomcat tomcat 207125 Feb  6 23:10 commons-daemon-native.tar.gz
-rw-r-----  1 tomcat tomcat  25145 Feb  6 23:10 commons-daemon.jar
-rwxr-x---  1 tomcat tomcat   1932 Feb 15 18:55 configtest.sh
-rwxr-x---  1 tomcat tomcat   8519 Feb 15 18:55 daemon.sh
-rwxr-x---  1 tomcat tomcat   1975 Feb 15 18:55 digest.sh
-rwxr-x---  1 tomcat tomcat   3690 Feb 15 18:55 setclasspath.sh
-rwxr-x---  1 tomcat tomcat   1912 Feb 15 18:55 shutdown.sh
-rwxr-xr-x  1 tomcat tomcat    147 Feb 16 15:25 start-tomcat.sh
-rwxr-x---  1 tomcat tomcat   1914 Feb 15 18:55 startup.sh
-rw-r-----  1 tomcat tomcat  49345 Feb  6 23:10 tomcat-juli.jar
-rwxr-x---  1 tomcat tomcat   5493 Feb 15 18:55 tool-wrapper.sh
-rwxr-x---  1 tomcat tomcat   1918 Feb 15 18:55 version.sh
```

### overlay / kernel 4.13
```
tomcat@50ccb899e250:~$ ls -la /usr/local/tomcat/bin
total 412
drwxr-x--- 1 tomcat tomcat   4096 Feb 16 15:10 .
drwxr-sr-x 1 tomcat tomcat   4096 Feb 16 15:10 ..
-rw-r----- 1 tomcat tomcat  34942 Feb  6 23:10 bootstrap.jar
-rw-r----- 1 tomcat tomcat   1664 Feb  6 23:12 catalina-tasks.xml
-rwxr-x--- 1 tomcat tomcat  23325 Feb 15 18:55 catalina.sh
-rw-r----- 1 tomcat tomcat 207125 Feb  6 23:10 commons-daemon-native.tar.gz
-rw-r----- 1 tomcat tomcat  25145 Feb  6 23:10 commons-daemon.jar
-rwxr-x--- 1 tomcat tomcat   1932 Feb 15 18:55 configtest.sh
-rwxr-x--- 1 tomcat tomcat   8519 Feb 15 18:55 daemon.sh
-rwxr-x--- 1 tomcat tomcat   1975 Feb 15 18:55 digest.sh
-rwxr-x--- 1 tomcat tomcat   3690 Feb 15 18:55 setclasspath.sh
-rwxr-x--- 1 tomcat tomcat   1912 Feb 15 18:55 shutdown.sh
-rwxrwxr-x 1 tomcat tomcat    147 Feb 16 15:09 start-tomcat.sh
-rwxr-x--- 1 tomcat tomcat   1914 Feb 15 18:55 startup.sh
-rw-r----- 1 tomcat tomcat  49345 Feb  6 23:10 tomcat-juli.jar
-rwxr-x--- 1 tomcat tomcat   5493 Feb 15 18:55 tool-wrapper.sh
-rwxr-x--- 1 tomcat tomcat   1918 Feb 15 18:55 version.sh
```

**Comment by kwilcox** [comment]
I think we can probably close this issue by adding a note that if people get `"catalina.sh": executable file not found in $PATH` or similar permission issues they should move away from `aufs` and upgrade their kernel.

**Comment by julienchastang** [comment]
Yeah, these `aufs` errors are horrible b/c they tend to hit you out of nowhere, and you have to spend a bunch of time figuring out what’s up. It is like the laws of the universe are turned upside down. At this juncture, it is appropriate to take a step back, and ask ourselves, aren’t computers supposed to make our lives easier? Anyway, hopefully you are on your way having concluded that `aufs` is the problem.
