### ISSUE TITLE
Rebuild unidata/tomcat-docker on DockerHub from latest tomcat

### ISSUE THREAD

**Issue by mwengren** [Unidata/tomcat-docker#56]
I was doing some testing with a downstream Docker image [axiom/docker-erddap](https://hub.docker.com/r/axiom/docker-erddap/) that is based off of unidata/tomcat-docker on Kubernetes (on GCP/GKE), and I ran into a thorny permission problem related to Tomcat directory permissions (/logs and /work).  

Because of how nodes are set up on GKE the system-level account that runs containers does not have proper permissions to write to those subdirectories under CATALINA_HOME, as a result no logs or runtime files can be written for any deployed webapps.  This has been fixed in the upstream tomcat [image](https://github.com/docker-library/tomcat/commit/ccf0fa74f05274f8e00e2a27ca0cc8e04d28f0ec), but the unidata/tomcat-docker hasn't been rebuilt since it was patched.  

I made my own fork of [unidata/tomcat-docker](https://hub.docker.com/r/mwengren/tomcat-unidata/) and [axiom/docker-erddap](https://hub.docker.com/r/mwengren/docker-erddap/) and was able to confirm a simple rebuild fixes the issue.  

Can both of these repos be rebuilt with the latest tomcat?

cc @kwilcox

**Comment by julienchastang** [comment]
I want to tackle this but I am getting stymied by https://github.com/tianon/gosu/issues/39. Proposed workarounds don't seem to work either. Will keep trying though...

**Comment by julienchastang** [comment]
[I refreshed the builds.](https://hub.docker.com/r/unidata/tomcat-docker/builds/)

Related: https://github.com/Unidata/tomcat-docker/issues/57

Give it a shot.

**Comment by mwengren** [comment]
Success!  I rebuilt my ERDDAP image with a new [tag](https://hub.docker.com/r/mwengren/docker-erddap/tags/) from unidata/tomcat-docker and permissions look good. 

@kwilcox If you can do the same for the main ERDDAP, that would be great.

**Comment by kwilcox** [comment]
@daf can you kick off the build for ERDDAP-docker?

**Comment by kwilcox** [comment]
And by that i mean axiom/docker-erddap

**Comment by daf** [comment]
I triggered rebuilds for both `latest` and `1.82` tags.

**Comment by mwengren** [comment]
We're good to go now I think.  Thanks for making these changes.  This sure was a head-scratcher when I first encountered the write errors.  I never figured out whether it was particular to running Kubernetes on GCP with their node setup, or more general in k8s, but some who tries what I did shouldn't have an issue anymore.
