### ISSUE TITLE
Can the user for the container not be root?

### ISSUE THREAD

**Issue by isuftin** [Unidata/tomcat-docker#68]
This is a very common security best practice in the community to not run the Docker container as the root user inside of the container. Currently, Tomcat does run as the tomcat user but when logging into the container via `docker exec ...` I am put in as the root user.  I wonder if this can be changed.

**Comment by julienchastang** [comment]
After entering the container via `docker exec`, you can "drop down" to user `tomcat` using `gosu` just in the way that is demonstrated in `entrypoint.sh`. It took a lot of tinkering to get this right so unless you have a better solution, I am inclined to leave things as is.

**Comment by isuftin** [comment]
@julienchastang Fair enough. I was concerned seeing me come in as root when `docker exec`-ing into the container. I know I can gosu down to tomcat but this also provides users the ability to get into the container as root in the first place. I see why it's done this way based on the startup scripting and what's being done in there. That being the case, I don't really have a better solution so I'll go ahead and close this out :)
