### ISSUE TITLE
Open Source License missing

### ISSUE THREAD

**Issue by ayeks** [Unidata/tomcat-docker#84]
Hey,

thanks for providing the scripts! Could you add a license to this repository please?

Best regards
Lars

**Comment by julienchastang** [comment]
I find licenses for Dockerfiles confusing, but I'm probably overthinking it.

**Comment by ayeks** [comment]
Thanks a lot. By having the license it is possible for me to integrate your scripts in our solutions and contribute to the open source scripts.

Cheers!
