### ISSUE TITLE
Changes in web.xml last November broke CORS for our thredds and erddap

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/tomcat-docker#87]
We run all of our services as docker containers, and we enable CORS for all services in the NGINX configuration file so we don't have to mess around with enabling CORS in various containers. 

This had been working fine but after upgrading our ERDDAP and THREDDS containers from last summer to the latest versions, we found that CORS was no longer working. 

We tracked down the problem to the changes here: https://github.com/Unidata/tomcat-docker/commit/43c612198a7f0091bfc50e786341b637190343c6

We got CORS working again by adding `web.xml` as a volume mounted file and removed these lines:

https://github.com/Unidata/tomcat-docker/commit/43c612198a7f0091bfc50e786341b637190343c6#diff-992c664978280ba817f14b6b744daa7fR619-R631

We also checked the THREDDS server on jetstream figuring it's also using this container, and CORS is not working there:
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fthredds-jetstream.unidata.ucar.edu%2Fthredds%2Fwms%2Fgrib%2FNCEP%2FGFS%2FGlobal_0p25deg%2FBest%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by rsignell-usgs** [comment]
ping @kwilcox and @dnowacki-usgs

**Comment by julienchastang** [comment]
I **believe** this was a security enhancement recommended by @oxelson. I wonder how thredds.ucar.edu handles this? In addition, you don't have to use that `web.xml`, but can mount your own and employ the one above for suggested use.  If this is a problem, perhaps this could be clarified with a comment in the `web.xml` suggesting you may not want this enhancement for situations like the one you describe. (Also ping @lesserwhirls.)

**Comment by p4block** [comment]
Kinda related to this, I've been trying to make our THREDDs able to respond to Godiva/other things hosted on domains different than the one used for THREDDs without much success. 

I've removed all cors headers and solved everything obvious that the browser complains about, but right now it's just returning 403 on a simple GetMetadata call (it works fine with curl, or within the same domain)

If anyone is doing this kind of "public THREDDs" I'd love to know how you got it to work.

**Comment by srstsavage** [comment]
Just now running into this, but agreed, it is not great that CORS is always enabled at the Tomcat layer. We use the same topology as rsignell described (nginx with CORS, expecting proxied services to not add additional CORS headers, which break things).

Are we open to using an env var to activate deletion of the web.xml CORS config at container startup time?

**Comment by julienchastang** [comment]
Thanks for the input and the comments, but I am sort of missing the point. If you need customization beyond what is provided, simply mount over the existing `web.xml` with whatever customization you want or need in your own `web.xml`. No need for any fancy `sed` stuff or additional complexity. I’d say this is the “Docker way”. (ping @robertej09 @oxelson )

**Comment by srstsavage** [comment]
Thanks, granted it's definitely possible to curate and mount your own `web.xml` with the desired edits. However, this is a much more complicated process than setting a boolean env var to correct what I consider improper default behavior (setting CORS headers on a service container). A user wanting to do so needs to copy the existing `web.xml` from this repo or container, make the desired edits, remember to pull in upstream changes when they are made in this repo, or do all of the above in a script for reproducibility. Or, just set `DISABLE_CORS=1` ;) 

I think you could make an equally compelling argument that the "Docker way" aka microservices approach is to use the [12 factor app](https://12factor.net/config) philosophy whenever possible, in this case using env vars for config to simplify deployment. Of course you can't make env var levers for every config, but again I think being able to disable CORS is important and would suggest disabling it by default if there weren't backwards compatibility concerns.
